
/**************************************************************
 *	
 *	coin, 8 bit, 11025Hz,
 *	1 channel, 10969 bytes/channel
 *	Total Size: 1 * 10969 + 4 (header) = 11013 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\coalt\Documents\cs2261\final project\1.0\final_project\coin.wav
 *	Time-stamp: Sun Dec 03 22:53:31 2017
 *	
 **************************************************************/

#ifndef __COINH__
#define __COINH__

#define COINFREQ 11025
#define COINLEN 10969

extern const unsigned char coin[10969];

#endif /* __COINH__ */
