
/**************************************************************
 *	
 *	hurt, 8 bit, 11025Hz,
 *	1 channel, 3734 bytes/channel
 *	Total Size: 1 * 3734 + 4 (header) = 3778 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\coalt\Documents\cs2261\final project\1.0\final_project\hurt.wav
 *	Time-stamp: Sun Dec 03 22:43:28 2017
 *	
 **************************************************************/

#ifndef __HURTH__
#define __HURTH__

#define HURTFREQ 11025
#define HURTLEN 3734

extern const unsigned char hurt[3734];

#endif /* __HURTH__ */
