
/**************************************************************
 *	
 *	laser, 8 bit, 11025Hz,
 *	1 channel, 1180 bytes/channel
 *	Total Size: 1 * 1180 + 4 (header) = 1224 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\coalt\Documents\cs2261\final project\beta\laser.wav
 *	Time-stamp: Tue Nov 28 22:41:39 2017
 *	
 **************************************************************/

#ifndef __LASERH__
#define __LASERH__

#define LASERFREQ 11025
#define LASERLEN 1180

extern const unsigned char laser[1180];

#endif /* __LASERH__ */
