
/**************************************************************
 *	
 *	loseSong, 8 bit, 11025Hz,
 *	1 channel, 455616 bytes/channel
 *	Total Size: 1 * 455616 + 4 (header) = 455660 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\coalt\Documents\cs2261\final project\1.0\final_project\loseSong.wav
 *	Time-stamp: Mon Dec 04 00:20:33 2017
 *	
 **************************************************************/

#ifndef __LOSESONGH__
#define __LOSESONGH__

#define LOSESONGFREQ 11025
#define LOSESONGLEN 455016

extern const unsigned char loseSong[455616];

#endif /* __LOSESONGH__ */
