
/**************************************************************
 *	
 *	song01, 8 bit, 11025Hz,
 *	1 channel, 1302562 bytes/channel
 *	Total Size: 1 * 1302562 + 4 (header) = 1302606 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\coalt\Documents\cs2261\final project\beta\song01.wav
 *	Time-stamp: Tue Nov 28 20:47:35 2017
 *	
 **************************************************************/

#ifndef __SONG01H__
#define __SONG01H__

#define SONG01FREQ 11025
#define SONG01LEN 1302062

extern const unsigned char song01[1302562];

#endif /* __SONG01H__ */
