
/**************************************************************
 *	
 *	title, 8 bit, 11025Hz,
 *	1 channel, 81625 bytes/channel
 *	Total Size: 1 * 81625 + 4 (header) = 81669 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\coalt\Documents\cs2261\final project\1.0\final_project\title.wav
 *	Time-stamp: Thu Nov 30 22:28:15 2017
 *	
 **************************************************************/

#ifndef __TITLEH__
#define __TITLEH__

#define TITLEFREQ 11025
#define TITLELEN 81240

extern const unsigned char title[81625];

#endif /* __TITLEH__ */
