
/**************************************************************
 *	
 *	victory, 8 bit, 11025Hz,
 *	1 channel, 756064 bytes/channel
 *	Total Size: 1 * 756064 + 4 (header) = 756108 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\coalt\Documents\cs2261\final project\1.0\final_project\victory.wav
 *	Time-stamp: Mon Dec 04 00:05:08 2017
 *	
 **************************************************************/

#ifndef __VICTORYH__
#define __VICTORYH__

#define VICTORYFREQ 11025
#define VICTORYLEN 755364

extern const unsigned char victory[756064];

#endif /* __VICTORYH__ */
